### ISSUE TITLE
Same song extracted multiple times

### ISSUE THREAD

**Issue by laurorual** [EnanoFurtivo/Osu-Mp3-Extractor#1] opened 2021-01-02 23:22 UTC
Hi! I just used your app to extract my Osu songs but i found a weird behave on it.
There was 2 or 3 songs that was extracted multiple times, like if every versions of the map (easy, hard, insane etc.) was a different song, but it wasnt.

Also, minor "bug" i found, my Osu folder is located at "AppData" folder and the folder selection window couldnt find it until i select on Explorer to show hidden files.

Anyways, thanks for the app!

**Comment by EnanoFurtivo** [comment] 2021-01-03 02:57
Hey thanks for the feedback. I thought this was a dead program lmao.

Regarding the issue of the app not showing you the path on the explorer, I'm not really sure if this can be solved on the app's end, as it has to do with how windows explorer works.

As for the issue regarding the multiple extractions. Please check if you have multiple difficulties of the same beatmapset on the collection you are extracting, as this is intended behavior. If that's not the case then please write again and I'll take some time to look into it.
![image](https://user-images.githubusercontent.com/31115763/103470583-bee0e980-4d52-11eb-9083-16b282c3c56f.png)

**Comment by laurorual** [comment] 2021-01-03 04:00
![Captura de tela 2021-01-03 005720](https://user-images.githubusercontent.com/755915/103471408-ba223280-4d5e-11eb-92ad-260ac459b0e7.png)

this is a screenshot of the folder for one of the beatmap that is exporting the same song for every difficulty.
this is the only beatmap i have in Osu for this song (This Game - Konomi Suzuki), so i think this isnt normal behavior, is it?

**Comment by EnanoFurtivo** [comment] 2021-01-03 05:47
Your problem is something like this, on the collection inside osu! you have multiple difficulties of the same beatmap set, here you have an screenshot of what I mean by that.

![image](https://user-images.githubusercontent.com/31115763/103472517-54897280-4d6d-11eb-87e2-7b1fa38e6dd6.png)

As you can see the collection "test" contains the 4 difficulties of the beatmapset 160201, wich is the one you provided on the screenshot. If this is how you have it set up then you will end up with 4 audio files. The fix for this is leaving only one difficuly in the collection like this.

![image](https://user-images.githubusercontent.com/31115763/103472587-e5604e00-4d6d-11eb-8676-b289bf88c65a.png)

**Comment by laurorual** [comment] 2021-01-04 02:52
i see! but i actually exported the complete library.
next time i'll set collections and try this out.
thanks for the app!

**Closed as completed** 2022-04-05 22:50 UTC
